language: csharp
mono: 3.12.0
solution: CSharpLogic.sln

script:
  - xbuild /p:Configuration=Debug CSharpLogic.sln

before_install:
  - sudo apt-get install nunit-console

before_script:
  - nuget restore CSharpLogic.sln
  
after_script:
  - nunit-console bin/Release/CSharpLogic.dll
